# Generated by Django 3.2.13 on 2022-07-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='adte_added',
            new_name='date_added',
        ),
    ]
